# Generated by Django 5.2.17 on 2026-09-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='medium', max_length=10)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_done', '-created_at'],
            },
        ),
    ]
